name: test
on: push

jobs:
 build:
   name: test
   # This job runs on Linux
   runs-on: linux
   env:
     IMAGE_NAME: node-test
     IMAGE_TAG: latest
   steps:
     - uses: actions/checkout@v1

     - name: Docker build
       run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

     - name: Test
       run: docker run --rm -i $IMAGE_NAME:$IMAGE_TAG yarn test
  
